### ISSUE TITLE
[FEAT] Chatting Room UI 구현

### ISSUE THREAD

**Issue by kms0233** [SOPT-all/35-COLLABORATION-iOS-LINKAREER#19]
## 🌟 Issue

Chatting Room UI 구현 예정입니닷!

## 📝 To-do

- [x] 채팅룸 Navbar 구현
- [x] NoticeView 구현
- [x] Other MessageCell 구현
- [x] My MessageCell 구현
- [x] CertificationPopUpView 구현
- [x] 텍스트 입력 View 구현

## 🕓 예상 작업 기한

- 11월 21일 ~ 11월 22일
